export enum Features {
  CRUD = 'CRUD',
  CONTEXT = 'React context usage',
  LOCAL_STORAGE = 'localStorage data storing',
  MUI = 'Material UI',
  HOOKS = 'React hooks',
  ASYNC = 'Asynchronous operations',
  APIS = 'Third party APIs',
  JS_CLASSES = 'Javascript classes & inheritance',
  DOM = 'DOM manipulation',
  CSS3 = 'Vanilla CSS',
  MVC = 'MVC pattern',
  ANIMATIONS = 'Animations',
  MOBILE = 'Mobile responsive design',
  BACKEND = 'Works with backend',
  HTTP_HOOK = 'Custom Http Hook',
  TOOLKIT = 'Redux toolkit',
  ASYNC_THUNKS = 'Thunk Middleware ',
}

export enum Techs {
  REACT = 'react',
  JS = 'javascript',
  HTML = 'html',
  CSS3 = 'css',
  TS = 'typescript',
  MOBX = 'mobx',
  REDUX = 'redux',
  NPM = 'npm',
  GITHUB = 'github',
  GIT = 'git',
  VSCODE = 'vscode',
  MUI = 'mui',
  FIREBASE = 'firebase',
}
